spring.application.name=clinica
#spring.datasource.url=jdbc:sqlite:src/main/resources/db/clinica.db
#spring.datasource.url=jdbc:sqlite=${DB_PATH}
spring.datasource.url=jdbc:sqlite:../../db/clinica.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.database-platform=com.example.config.SQLiteDialect
